### ISSUE TITLE
Submission Stats results are not giving the required csv file

### ISSUE THREAD

**Issue by gjkaur** [Wenxuan-1119/TransBTS#6] opened 2021-04-03 15:06 UTC
I have used your code and tested it to predict the segmentation results for validation set. Then I submitted the generated segmentation  files on cbica evaluation portal for BraTS 2020 validation segmentation task.
My job is completed but in zip file I am not receiving any csv file with segmentation scores.
[Results-733562074827703492.zip](https://github.com/Wenxuan-1119/TransBTS/files/6252805/Results-733562074827703492.zip)

Please help.

**Comment by Wenxuan-1119** [comment] 2021-04-04 04:45
Actually, I met the same problem when I test on the BraTS 2020 validation segmentation task. At the beginning, we intended to evaluate our model on BraTS 2020 and BraTS2019, but since I met this problem, we did not solve it until now. I am not sure the problem is because of the inference code or the official testing server. I've already sent the email to the official contact but have not got any reply. I don't know where the mistakes may be, maybe we can dicuss a little about it.

**Comment by Wenxuan-1119** [comment] 2021-04-06 02:25
Sorry to bother , have you solved this problem? Please help.

**Comment by gjkaur** [comment] 2021-04-06 04:13
No. I am not able to solve this problem. I have also sent mail to some official persons but no reply from their side.

**Comment by Wenxuan-1119** [comment] 2021-04-06 05:05
Do you think there's maybe some problem in code for inference? Maybe it's not because of the official server.

**Comment by gjkaur** [comment] 2021-04-06 06:49
I think its server problem. Because last week I replicated one more code from github and submitted the results on CBICA for evaluation. The results were evaluated perfectly with csv file. Then for this week, I replicated your code and submitted the generated nifti files for evaluation. I received mail for job completion but csv file was not there. Then I thought It might be due to 240*240*160 file dimension. Then I modified your code for 240*240*155 dimension instead of 240*240*160 and submitted again the segmented files for evaluation. But same issue was there. 

Then to cross check that whether this problem is particularly with the files generated by using your code, I resubmitted the last week files gain. But server was still not generating csv file.

In the last, I opened an issue here that how you were able to generate results for Brats 2020 dataset?

**Comment by gjkaur** [comment] 2021-04-06 06:50
I am thinking of resubmitting the previous files again to check once more.

**Comment by gjkaur** [comment] 2021-04-06 06:52
I used two different accounts also to check evaluation results. But no use.

**Comment by Wenxuan-1119** [comment] 2021-04-06 09:17
The one more code you mentioned from github is which repo? Can you give me a link? After getting your reply, I can tell that it's because of something wrong with my inference code when testing on BraTS 2020.

**Comment by gjkaur** [comment] 2021-04-06 13:03
Ok sure.
https://github.com/lescientifik/open_brats2020

Kindly inform me if you are able to do perfect inference generation.

**Comment by Wenxuan-1119** [comment] 2021-04-06 13:11
Yeah, for sure. Thank you. I won't close this issue until we figure out the problem, and I will inform you when I solve this.

**Comment by gjkaur** [comment] 2021-04-06 13:18
ok, welcome. thanks to you too for making your code available. and responding to my query as well.

**Comment by Wenxuan-1119** [comment] 2021-04-06 13:36
That's all right. My pleasure.

**Comment by Wenxuan-1119** [comment] 2021-04-07 05:40
Sorry to bother, can you offer me the file of segmentation results generated perfectly by the other code you mentioned? So I can easily compare it with my code.

**Comment by gjkaur** [comment] 2021-04-08 04:26
[BraTS20_Validation_005.nii.gz](https://github.com/Wenxuan-1119/TransBTS/files/6276006/BraTS20_Validation_005.nii.gz)
[BraTS20_Validation_001.nii.gz](https://github.com/Wenxuan-1119/TransBTS/files/6276007/BraTS20_Validation_001.nii.gz)
[BraTS20_Validation_002.nii.gz](https://github.com/Wenxuan-1119/TransBTS/files/6276008/BraTS20_Validation_002.nii.gz)
[BraTS20_Validation_003.nii.gz](https://github.com/Wenxuan-1119/TransBTS/files/6276009/BraTS20_Validation_003.nii.gz)
[BraTS20_Validation_004.nii.gz](https://github.com/Wenxuan-1119/TransBTS/files/6276010/BraTS20_Validation_004.nii.gz)

**Comment by Qiran-Jia** [comment] 2021-04-18 07:47
I think for the 2020 data set, the labeled segmentation have a size of (155, 240, 240), while in your prediction.py file you set the segmentation output to be the size (160, 240, 240). Will this be the reason?

**Comment by Wenxuan-1119** [comment] 2021-04-18 07:53
Thanks for your advice sincerely. But I don't think it's the reason. Because although we pad the image to (160, 240, 240), but after the function of tailor_and_concat, the output size returned is (155, 240, 240). I am really looking forward to more your advice, thanks.

**Comment by caixh39** [comment] 2021-04-21 08:30
I also meet the problem, then soloved it by forced conveted the predict result *.nii.gz file space and coordinate into validation *t1.nii.gz volume. 
But the result is no good:
![image](https://user-images.githubusercontent.com/21239321/115522505-bdfea400-a2be-11eb-943c-33da1e85fd91.png)

**Comment by Wenxuan-1119** [comment] 2021-04-23 07:45
Thanks for your reply. But even though you get the final scores in your way, the scores in the csv file are clearly unnormal.

**Comment by caixh39** [comment] 2021-04-23 08:43
yes, I also think had wrong!

**Comment by Wenxuan-1119** [comment] 2021-04-23 09:03
Do you thing where might be the problem in the code that may lead to this error?

**Comment by Wenxuan-1119** [comment] 2021-04-25 15:47
gjkaur, bro, it's been a while since our last talk. Recently I've been compared our code with https://github.com/lescientifik/open_brats2020 that you offered, there are some progress for checking the problem in our code. After make sure that both our submission file and the submission file of open_brats2020 have the same shape and same file name,  I also make sure that it's not because of the way of WriteImage or the data type of np.zeros( ), so I believe the problem maybe because our code don't have these following rows:

ref_img = sitk.ReadImage(ref_img_path)
labelmap.CopyInformation(ref_img)

Actually I do not understand the ref_img_path is for what purpose ,and maybe these two rows can keep the previous information from ref_img_path which is necessary. Can you help me out here? What do you think? Looking forward to your reply.

**Comment by Wenxuan-1119** [comment] 2021-04-27 11:50
I finally solved the evaluation problem on BraTS 2020. This error is because that the submission files generated by our codes do not have the same physical dimension as https://github.com/lescientifik/open_brats2020, which is necessary for the final evaluation. The error can be solved by adjusting the code of predict.py. Here are the extra codes for fixing this error when you tryna test on BraTS 2020.
![image](https://user-images.githubusercontent.com/56334198/116236478-b2651e80-a791-11eb-99fa-6eda91656df5.png)

**Closed by Wenxuan-1119** 2021-04-27 11:50 UTC

**Comment by gjkaur** [comment] 2021-04-27 16:58
I will try this modification. Thanks a lot.

**Comment by gjkaur** [comment] 2021-06-30 05:57
wenxuan can u plz do these changes in predict file as u are able to get results for brats 2020 data as well. It will be very helpful of u.

**Comment by wangyunyuwyy** [comment] 2023-05-12 02:19
> 

Hello, I'm very sorry to bother you. I would like to ask if you can obtain the CSV file of the test results on Brats 2020. I have been trying repeatedly but have failed. I hope to receive your reply. Thank you very much.

**Comment by Eight3H** [comment] 2024-09-02 08:35
> > 
> 
> Hello, I'm very sorry to bother you. I would like to ask if you can obtain the CSV file of the test results on Brats 2020. I have been trying repeatedly but have failed. I hope to receive your reply. Thank you very much.

你好，请问你解决了吗
